Resolve deprecation of selem argument (now footprint) in skimage.morphology.dilation
PAIR-code/saliency pull request #92
Opened 2023-04-10 20:07 UTC by davedgd

Recent versions of scikit-image have completely deprecated the `selem` argument in favor of `dilation`:

[skimage.morphology.dilation](https://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.dilation)
[Complete deprecation of selem parameter](https://github.com/scikit-image/scikit-image/pull/6583/commits/7430c415ccdf716c1aca7226f03ede85e12e1ba9)

This minor patch to [xrai.py](https://github.com/PAIR-code/saliency/blob/master/saliency/core/xrai.py#L126) resolves the issue on line 126.

2023-07-24 16:03 UTC, mantasu requested changes
I suggest renaming all 3 occurrences of `selem` to `footprint` for consistency.

2023-07-24 18:20 UTC, davedgd commented
@mantasu: Makes sense -- updated all three references from `selem` to `footprint` -- thanks!

2023-07-24 20:42 UTC, mantasu approved these changes
I hope they merge this soon

2023-11-23 02:26 UTC, omarirfa approved these changes
Just tested this out, was wondering why the example notebook was breaking. I updated the xrai.py file with the changes mentioned and it worked like charm! Please merge this so other ppl will not face this error!

2024-02-29 08:21 UTC, takumiohym approved these changes
LGTM

2024-02-29 13:59 UTC, gkapish approved these changes

2024-02-29 13:59 UTC, merged

2024-03-04 14:53 UTC, tolga-b commented
Thanks for submitting this fix!